### ISSUE TITLE
problem with recover_spectral_density

### ISSUE THREAD

**Issue by Fangwq** [wjmaddox/spectralgp#1]
Hi, I run the code and it turns out an error in the code:
`ModuleNotFoundError: No module named 'spectralgp.kernels.recover_spectral_density`.
It seems that the code, in the `spectralgp/kernels` folder, is lack of `recover_spectral_density.py` file. Would you please upload this file ? Thank you very much!

**Comment by wjmaddox** [comment]
Good catch, sorry for forgetting about it.

It's now in the repo: https://github.com/wjmaddox/spectralgp/blob/master/spectralgp/kernels/recover_spectral_density.py
