### ISSUE TITLE
AttributeError: module 'spectralgp.utils' has no attribute 'link_function'

### ISSUE THREAD

**Issue by Fangwq** [wjmaddox/spectralgp#4]
I run the code `run_with_para_models.py` and encounter this problem. It seems that the `link_function` is missing in `utils.py`  file. Would you like to check it? thank you very much!

**Comment by wjmaddox** [comment]
I think that I just resolved it. Can you try now?

**Comment by Fangwq** [comment]
Yeah, this problem solved, thank you very much. However, another problem comes up: `AttributeError: 'SpectralGPKernel' object has no attribute 'latent_mean'` in `mu_init = data_mod.covar_module.latent_mean(omega).detach()`.

**Comment by wjmaddox** [comment]
Ugh, I'll take a detailed look later today/tomorrow. Sorry for the issue

**Comment by Fangwq** [comment]
OK, do not say sorry about that. It's so nice to make your codes public, or it will takes me weeks or months to repeat your work.

**Comment by salkj** [comment]
:)

**Comment by wjmaddox** [comment]
`run_with_para_models` should run now with the most recent commit (bf9af3f). 

Basically, when we updated the code to use the optimal spectral spacing (broadly Appendix D of https://arxiv.org/pdf/1910.13565.pdf) we forgot to update a lot of the experiments scripts :(. 

Feel free to close the issue if you're able to run everything.

**Comment by Fangwq** [comment]
It works. Thanks for your help!
